# Generated by Django 5.2.12 on 2026-04-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_classroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassRoom',
        ),
    ]
