# Generated by Django 5.2.12 on 2026-04-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(related_name='students', to='record.classroom'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.student')),
            ],
        ),
    ]
