# Generated by Django 5.2.12 on 2026-04-14 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_remove_student_classroom_student_classes_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.classroom'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
