# Generated by Django 5.2.12 on 2026-04-14 20:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_remove_student_classes_student_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
