# Generated by Django 5.2.12 on 2026-04-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.activity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.student')),
            ],
            options={
                'unique_together': {('student', 'activity')},
            },
        ),
    ]
