# Generated by Django 5.2.12 on 2026-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_studentactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='record.classroom'),
        ),
    ]
