# Generated by Django 5.2.12 on 2026-04-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_remove_student_classroom_student_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='record.classroom'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='StudentActivity',
        ),
    ]
