# Generated by Django 5.2.12 on 2026-04-15 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_remove_student_classrooms_student_classroom_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
