# Generated by Django 5.2.12 on 2026-04-15 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_activity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
