# Generated by Django 5.2.12 on 2026-04-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0021_attendancesession_attendancerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Late', 'Late'), ('Absent', 'Absent')], max_length=10, null=True),
        ),
    ]
